### ISSUE TITLE
images not shown on iOS devices

### ISSUE THREAD

**Issue by chuckgit123** [multicolor-rgb/newgalleryfolder-for-bluditcms#5]
Hi! First of all: Thanks for this amazing plugin - it is exactly what I need to make bludit work for my needs :smiley: 

I just have one issue: images are not shown on iOS devices - all I get there is a gray border with empty (white) content (see below). I tried Safari, Brave, Firefox and Chrome on iOS - all of them have this issue. The funny thing is, that it works without issue on Chrome on Android, so it seems to be iOS specific and not browser specific.

I also tried several themes, and both, v3 and v4. 

This is what is shown instead of the image:

<img width="424" alt="bludit-empty-img" src="https://user-images.githubusercontent.com/59502680/179391234-f60d401f-dae6-41c8-b635-2ddd615e3a8b.png">

**Comment by multicolor-rgb** [comment]
ok, i will check this on this week and update for correct work:) Stay tuned.

**Comment by chuckgit123** [comment]
I think I know what the issue is: the link to the images (and the thumbnails) are build using the host name and the relative path of the image - which leads to a dot in the URL after the hostname.
Example:
- Hostname: `https://myblog`
- Image: `./bl-content/uploads/pages/926ba1d0c6655...`

That results in an image URL like `https://myblog./bl-content/uploads/pages/926ba1d0c6655...`. The extra `.` after `myblog` seems to lead to trouble on iOS devices.

**Comment by multicolor-rgb** [comment]
Hey, yes i know that problem and i fixed this- soon new version with your suggestion. Now i have a lot of work, this is why i no release now. give me one, two days

**Comment by chuckgit123** [comment]
Sure :smile: (and sorry if I seemed pushy, wasn't my intention :fearful:).

**Comment by multicolor-rgb** [comment]
v 5.0 release :)

**Comment by chuckgit123** [comment]
Hm, sorry to say, but as far as I can see, there is still a dot (`.`) between the hostname and the path (e.g. `https://my.web.site./bl-content/...`), and therefore still not working on iOS devices).

**Comment by multicolor-rgb** [comment]
Do you clean cache? What version PHP?
sob., 23.07.2022, 9:48 AM użytkownik chuckgit123 ***@***.***>
napisał:

**Comment by multicolor-rgb** [comment]
Do you have this dot on thumbnail or direct path?

sob., 23.07.2022, 10:34 AM użytkownik Multicolor Studio Reklamy <
***@***.***> napisał:

**Comment by multicolor-rgb** [comment]
Ok i find fixes.

**Comment by multicolor-rgb** [comment]
https://github.com/multicolor-rgb/newgalleryfolder-for-bluditcms/raw/main/newgalleryfolder-v501.zip please check now

**Comment by chuckgit123** [comment]
jep - now it works! Awsome, thanks alot! :smile:
